// Auto-generated by scripts/generate-bundled-provider-auth-env-vars.mjs. Do not edit directly.

export const BUNDLED_PROVIDER_AUTH_ENV_VAR_CANDIDATES = {
  anthropic: ["ANTHROPIC_OAUTH_TOKEN", "ANTHROPIC_API_KEY"],
  brave: ["BRAVE_API_KEY"],
  exa: ["EXA_API_KEY"],
  firecrawl: ["FIRECRAWL_API_KEY"],
  "github-copilot": ["COPILOT_GITHUB_TOKEN", "GH_TOKEN", "GITHUB_TOKEN"],
  google: ["GEMINI_API_KEY", "GOOGLE_API_KEY"],
  kilocode: ["KILOCODE_API_KEY"],
  kimi: ["KIMI_API_KEY", "KIMICODE_API_KEY"],
  "kimi-coding": ["KIMI_API_KEY", "KIMICODE_API_KEY"],
  minimax: ["MINIMAX_API_KEY"],
  "minimax-portal": ["MINIMAX_OAUTH_TOKEN", "MINIMAX_API_KEY"],
  moonshot: ["MOONSHOT_API_KEY"],
  openai: ["OPENAI_API_KEY"],
  openrouter: ["OPENROUTER_API_KEY"],
  perplexity: ["PERPLEXITY_API_KEY", "OPENROUTER_API_KEY"],
  tavily: ["TAVILY_API_KEY"],
  zai: ["ZAI_API_KEY", "Z_AI_API_KEY"],
} as const satisfies Record<string, readonly string[]>;
